const Group=require('../models').Group;

exports.insertGroup=(req,res,next)=>{
    Group.create({
            gr_id:req.body.gr_id,
            gr_subject:req.body.gr_subject,
            gr_use_access:req.body.gr_use_access,
            gr_device:req.body.gr_device,
            gr_order:req.body.gr_order
        }).then((result)=>{
            res.json({
                message:1,
                dasta:result
            });
        }).catch((error)=>{
            console.error(error);
            res.status(500).json({
                message:0,
                data:error
            })
            next(error);
        });
    };
    
exports.updateGroup=(req,res,next)=>{
    Group.update({
       gr_id:req.body.gr_id,
       gr_subject:req.body.gr_subject,
       gr_use_access:req.body.gr_use_access,
       gr_device:req.body.gr_device,
       gr_order:req.body.gr_order
   },{
       where:{
           gr_id:req.body.gr_id  
       }
   }).then((result)=>{
       res.json({
           message:1,
           data:result
       });
   }).catch((error)=>{
       console.error(error);
       res.status(500).json({
           message:0,
           data:error
       });
       next(error);
   });
};

exports.deleteGroup=(req,res,next)=>{
    Group.destroy({
       where:{
           gr_id:req.body.gr_id  
       }
   }).then((result)=>{
       res.json({
           message:1,
           data:result
       });
   }).catch((error)=>{
       console.error(error);
       res.status(500).json({
           message:0,
           data:error
       });
       next(error);
   });
};